### ISSUE TITLE
Make Everything Dojo compatible with the new AoPS

### ISSUE THREAD

**Issue by tyxchen** [Deeg-Kim/Everything-Dojo#44]
A brand-new version of AoPS was just released today, and we will have to update a few things to account for changes to the blog HTML.

These changes also mean that the majority of themes in the database are likely broken, so we should probably label themes with their compatibility with the new site as authors start updating them.

**Comment by PythonNut** [comment]
Out of curiosity, where was the new blog HTML announced? It doesn't look like it breaks anything out of the ordinary for `libre`, which is probably one of the most fragile themes ever.

**Comment by tyxchen** [comment]
@PythonNut well, for one thing, the class of quotes have been changed to `bbcode_quote(_head|_body)?`, and there are substantial changes to the navigation bar, so I'm surprised nothing is broken for Libre.

I forgot when it was announced, but it was probably somewhere in one of the feedback threads.

**Comment by PythonNut** [comment]
@tyxchen wow, you don't say. It only just refreshed for me, and it broke _everything_. I'm actually feeling a little depressed because there's no way I have time to fix it.
